// This file is generated by scripts/generate-locales.mjs.
export const translations = {
  ja: {
    common: {
      optional: "任意",
      cancel: "キャンセル",
      back: "前の画面に戻る",
      settings: "設定",
      close: "閉じる",
      retry: "もう一度試す",
      delete: "削除する",
      no_image: "写真なし",
      loading: "読み込んでいます…",
    },
    rating: {
      buy_again: {
        label: "また買う",
        short: "また買う",
      },
      buy_if_cheap: {
        label: "安ければ買う",
        short: "安ければ",
      },
      maybe: {
        label: "微妙",
        short: "微妙",
      },
      never_again: {
        label: "二度と買わない",
        short: "避ける",
      },
    },
    tabs: {
      home: "ホーム",
      products: "商品一覧",
    },
    home: {
      settings_label: "設定を開く",
      title: "もう迷わない、\n買い物メモ。",
      subtitle: "買ってよかったものも、\nもう買わないものも、次の買い物へ。",
      scan: "バーコードをスキャン",
      scan_description: "登録済みなら、評価とメモをすぐ確認。",
      manual_add: "商品を手動登録",
      buy_again_count: "また買う",
      never_again_count: "二度と買わない",
      recent: "最近登録した商品",
      view_all: "すべて見る ›",
      empty_title: "まだ商品がありません",
      empty_description: "まずは、最近買ったものをひとつ記録してみましょう。",
      first_add: "最初の商品を登録",
    },
    products: {
      item_count_one: "1件",
      item_count_other: "{count}件",
      title: "商品一覧",
      add_label: "商品を登録する",
      search_placeholder: "商品名・ブランド・バーコードで検索",
      clear_search: "検索をクリア",
      all: "すべて",
      result_count_one: "1件の記録",
      result_count_other: "{count}件の記録",
      empty_title: "最初の商品を登録しましょう",
      empty_description:
        "バーコードをスキャンするか、商品名を手入力して記録できます。",
      no_results_title: "見つかりませんでした",
      no_results_description: "検索語や評価フィルターを変えて試してください。",
    },
    scan: {
      permission_icon_label: "カメラ",
      permission_title: "カメラでバーコードを読み取る",
      permission_description:
        "カメラへのアクセスを許可すると、商品をすばやく検索できます。",
      allow_camera: "カメラを許可する",
      open_settings: "設定を開く",
      preparing_camera: "カメラを準備しています…",
      close: "スキャンを閉じる",
      title: "バーコードをスキャン",
      helper: "JAN、EAN、UPCバーコードを枠の中に合わせてください",
      manual_title: "番号を直接入力",
      barcode_placeholder: "バーコード番号",
      search: "バーコードを検索",
      finding: "商品情報を確認しています…",
    },
    form: {
      loading: "商品を読み込んでいます…",
      create_title: "商品を登録",
      edit_title: "商品を編集",
      create_heading: "次の自分へ、ひとこと。",
      edit_heading: "記録を整える。",
      create_description:
        "評価はあとからでも変えられます。今の印象を残しておきましょう。",
      edit_description: "今の自分の感覚に合わせて、評価やメモを更新できます。",
      lookup_title: "商品情報を確認しています",
      lookup_description:
        "見つかった情報を候補として入力します。必要なら保存前に編集できます。",
      lookup_not_found: "商品情報が見つかりませんでした。手入力できます。",
      lookup_failed: "商品情報を取得できませんでした。手入力できます。",
      auto_fill_title: "商品情報を自動入力しました",
      auto_fill_description:
        "Open Food Factsの情報です。内容を確認してから保存してください。",
      image_change: "写真を変更",
      image_add: "商品写真を追加",
      image_remove: "写真を削除",
      product_name: "商品名",
      product_name_placeholder: "例：無糖カフェラテ",
      barcode: "バーコード",
      barcode_placeholder: "スキャンまたは入力",
      brand: "ブランド",
      brand_placeholder: "例：メーカー名",
      rating: "評価",
      note: "メモ",
      note_placeholder: "味、使い心地、買った場所など",
      saving: "保存中…",
      register: "商品を登録する",
      save_changes: "変更を保存",
    },
    detail: {
      load_failed: "商品を読み込めませんでした。",
      not_found: "商品が見つかりません",
      back_to_products: "商品一覧へ戻る",
      delete_title: "この商品を削除しますか？",
      delete_description: "削除した記録は元に戻せません。",
      delete_failed: "商品を削除できませんでした。",
      title: "商品詳細",
      edit_label: "商品を編集する",
      next_buy: "次に買うなら",
      avoid_next: "次は避ける",
      current_rating: "いまの評価",
      note_label: "メモ",
      no_note: "メモはまだありません。",
      registered_at: "登録日",
      updated_at: "更新日",
      edit_record: "この記録を編集する",
      delete_product: "この商品を削除",
    },
    errors: {
      barcode_required: "バーコードを入力してください。",
      product_name_required: "商品名を入力してください。",
      product_name_too_long: "商品名は120文字以内で入力してください。",
      brand_too_long: "ブランドは100文字以内で入力してください。",
      note_too_long: "メモは2000文字以内で入力してください。",
      barcode_digits_only: "バーコードは数字で入力してください。",
      lookup_failed: "商品を検索できませんでした。もう一度試してください。",
      product_not_found: "商品が見つかりません。",
      product_load_failed: "商品を読み込めませんでした。",
      photo_select_failed:
        "写真を選択できませんでした。もう一度試してください。",
      save_failed: "保存に失敗しました。",
      register_failed: "商品を登録できませんでした。",
      duplicate_barcode:
        "このバーコードの商品はすでに登録されています。既存の記録を編集してください。",
    },
    database: {
      load_failed_title: "記録を読み込めませんでした",
      load_failed_description:
        "アプリを再起動しても改善しない場合は、端末の空き容量を確認してください。",
    },
    settings: {
      title: "設定",
      language_title: "表示言語",
      language_description:
        "アプリの表示言語を選べます。システム設定に従う場合は端末の言語を使います。",
      system: "システム設定に従う",
      system_description: "日本語端末は日本語、それ以外はEnglishを使います。",
      japanese: "日本語",
      japanese_description: "アプリを日本語で表示します。",
      english: "English",
      english_description: "Display the app in English.",
      current: "現在の設定：{language}",
      product_language_note:
        "バーコード検索時の商品名も、この言語を優先します。",
      language_save_failed: "表示言語を保存できませんでした。",
      data_title: "データとプライバシー",
      data_description:
        "商品記録と写真はこの端末に保存されます。アプリを削除すると記録を失う可能性があります。",
      privacy_policy: "プライバシーポリシー",
      privacy_description:
        "保存する情報と外部サービスへの問い合わせについて確認できます。",
      terms: "利用規約",
      terms_description:
        "アプリの利用条件と買い切りアンロックについて確認できます。",
      accessibility: "アクセシビリティ方針",
      accessibility_description:
        "対応方針、代替手段、お問い合わせ先を確認できます。",
      attribution_title: "商品情報の提供元",
      attribution_description:
        "商品名、ブランド、画像の候補にOpen Food Factsを使用しています。",
      attribution_link: "Open Food Factsを開く",
    },
    purchase: {
      title: "買い切りアンロック",
      description:
        "無料版は商品を20件まで登録できます。買い切りで登録数の上限を解除できます。",
      price: "価格：{price}",
      price_unavailable: "価格はストアで表示されます",
      unlocked: "アンロック済み",
      unlock: "買い切りで解除する",
      restore: "購入を復元する",
      dev_build_required:
        "購入機能はApp StoreまたはGoogle Playの実機用ビルドで利用できます。",
      limit_title: "無料版の登録上限に達しました",
      limit_description:
        "無料版では商品を{count}件まで登録できます。既存の記録は引き続き閲覧、編集、削除できます。",
      limit_blocked: "新しい商品を登録するには、買い切りアンロックが必要です。",
      purchase_failed: "購入を完了できませんでした。",
      restore_failed: "購入を復元できませんでした。",
      finish_failed: "購入の確認を完了できませんでした。",
      store_unavailable: "購入ストアに接続できませんでした。",
    },
    terms: {
      title: "利用規約",
      intro: "buy-againは、購入した商品の印象を記録する個人用メモアプリです。",
      use_title: "サービスの性質",
      use_body:
        "在庫、発注、会計、品質管理を行う業務システムではありません。記録を食品の安全性、アレルギー、健康状態、医療上の判断の根拠に使用しないでください。",
      storage_title: "データの保存",
      storage_body:
        "記録と写真は端末に保存されます。永続性、完全性、利用可能性、復旧可能性を保証しません。故障、紛失、OSの処理、アプリ削除などでデータが失われることがあります。本アプリを唯一の保存先にしないでください。",
      external_title: "外部サービス",
      external_body:
        "バーコード検索のOpen Food Factsについて、情報の正確性、完全性、最新性を保証しません。通信障害、停止、仕様変更で利用できない場合があります。",
      purchase_title: "買い切りアンロック",
      purchase_body:
        "無料版は商品を20件まで新規登録できます。買い切りアンロックはサブスクリプションではありません。価格、税、返金、購入履歴、復元は各ストアの規約と適用法令に従います。",
      disclaimer_title: "免責と責任",
      disclaimer_body:
        "適用法令で許される範囲で、本アプリまたは外部サービスの利用による損害について責任を負いません。ただし、法令により制限できない責任、故意または重過失による責任などを除きます。",
      changes_title: "規約の変更",
      changes_body:
        "必要に応じて規約を変更することがあります。変更後の規約は、本アプリまたは配布ページで告知した時点から適用します。",
      law_title: "準拠法と管轄",
      law_body:
        "本規約は日本法に準拠します。紛争は、適用法令が定める管轄裁判所によって解決します。",
      contact_title: "お問い合わせ",
      contact_body:
        "開発者：naoki-webdev\nお問い合わせ：https://github.com/naoki-webdev/buy-again/issues",
    },
    accessibility: {
      title: "アクセシビリティ",
      intro:
        "VoiceOverとTalkBackで操作しやすい画面、文字サイズを大きくした場合にも確認しやすいレイアウトを目指して改善しています。",
      interaction_title: "操作と表示",
      interaction_body:
        "重要な操作には読み上げ用の名前を設定し、評価は色だけでなくラベルでも示します。大きな文字設定や画面サイズによる表示の変化を継続的に確認します。",
      alternative_title: "代替手段",
      alternative_body:
        "バーコードはカメラを使わず番号を手入力できます。カメラや写真へのアクセスを許可しなくても、手入力と写真なしの記録を利用できます。",
      standard_title: "参照基準",
      standard_body:
        "WCAG 2.2 AAを参照していますが、本アプリが同基準に完全準拠していることを表明するものではありません。",
      contact_title: "お問い合わせ",
      contact_body:
        "利用上の問題や改善提案はhttps://github.com/naoki-webdev/buy-again/issuesまでお知らせください。",
    },
    privacy: {
      title: "プライバシーとデータ",
      intro:
        "buy-againは、買った商品の記録を端末内で管理する個人用アプリです。",
      local_title: "端末内に保存する情報",
      local_body:
        "商品名、ブランド、バーコード、評価、メモ、登録日時、更新日時、商品写真を端末内に保存します。商品記録およびアプリ内に保存した商品写真（ユーザーが選択した写真やOpen Food Factsから取得した画像）を、開発者のサーバーへ送信することはありません。商品記録は、ユーザーがアプリ内で削除するか、アプリを削除するまで端末内に保持されます。アカウント登録、広告、アクセス解析、開発者が運営するサーバーへのクラウド同期は行いません。端末のOSバックアップ設定によっては、GoogleまたはAppleが提供するバックアップ機能の対象となる場合があります。",
      network_title: "Open Food Factsへの問い合わせ",
      network_body:
        "未登録の食品バーコードを確認するとき、アプリはバーコード番号と表示言語をOpen Food Factsへ送信します。商品記録や写真は検索リクエストに含めません。APIリクエストには、アプリ名、バージョン、公開リポジトリURLを含むUser-Agentも設定します。取得した商品名、ブランド、画像は保存前に確認と編集ができます。Open Food Facts側での情報の保持と削除には、同サービスのプライバシーポリシーと利用条件が適用されます。buy-againの開発者は、Open Food Facts側に保存された情報を管理しません。",
      permissions_title: "端末の権限",
      permissions_body:
        "カメラはバーコード読み取り時に使用します。写真へのアクセスは商品写真の選択時に使用します。どちらも許可しなくても、手入力と写真なしの記録は利用できます。カメラおよび写真へのアクセス許可は、端末の設定からいつでも変更または取り消すことができます。",
      security_title: "安全な取り扱い",
      security_body:
        "商品記録と写真は、アプリ専用の端末内領域に保存します。Open Food Factsとの通信にはHTTPSを使用します。",
      deletion_title: "削除",
      deletion_body:
        "商品詳細画面から商品記録を削除できます。商品記録を削除すると、buy-againが端末内に保存した商品写真も削除します。Open Food Factsへ送信したバーコードの削除や、同サービスでのデータ処理に関する問い合わせは、同サービスのプライバシーポリシーに記載された方法で行ってください。",
      third_party_title: "第三者サービスとライセンス",
      third_party_body:
        "商品情報はOpen Food Factsのデータを利用しています。データベースはOpen Database License（ODbL）、個別のデータ内容はDatabase Contents License、商品画像はCreative Commons Attribution-ShareAlike（CC BY-SA）の条件で提供されています。ライセンスの詳細と再利用条件は、Open Food Factsの公式サイトで確認してください。",
      purchase_title: "App StoreとGoogle Playの購入",
      purchase_body:
        "買い切りアンロックを利用する場合、決済情報はAppleまたはGoogleが処理します。buy-againの開発者はカード情報を取得しません。購入状態の確認には、各ストアが提供する購入情報をアプリが利用します。購入、返金、請求履歴には各ストアのプライバシーポリシーと利用規約が適用されます。",
      contact_title: "開発者情報とお問い合わせ",
      contact_body:
        "開発者：naoki-webdev\nプライバシーに関するお問い合わせ：https://github.com/naoki-webdev/buy-again/issues",
      off_link: "Open Food Factsのサイトを開く",
    },
    messages: {
      product_created: "商品を登録しました",
      product_updated: "変更を保存しました",
      product_deleted: "商品を削除しました",
    },
  },
  en: {
    common: {
      optional: "Optional",
      cancel: "Cancel",
      back: "Back",
      settings: "Settings",
      close: "Close",
      retry: "Try again",
      delete: "Delete",
      no_image: "No photo",
      loading: "Loading…",
    },
    rating: {
      buy_again: {
        label: "Buy again",
        short: "Buy again",
      },
      buy_if_cheap: {
        label: "Buy if cheap",
        short: "If cheap",
      },
      maybe: {
        label: "Maybe",
        short: "Maybe",
      },
      never_again: {
        label: "Never again",
        short: "Avoid",
      },
    },
    tabs: {
      home: "Home",
      products: "Products",
    },
    home: {
      settings_label: "Open settings",
      title: "Never wonder again,\nyour shopping memory.",
      subtitle: "Remember what you loved,\nand what you will skip next time.",
      scan: "Scan a barcode",
      scan_description: "See your rating and notes right away.",
      manual_add: "Add a product manually",
      buy_again_count: "Buy again",
      never_again_count: "Never again",
      recent: "Recently added",
      view_all: "View all ›",
      empty_title: "No products yet",
      empty_description: "Start by saving something you bought recently.",
      first_add: "Add your first product",
    },
    products: {
      item_count_one: "1 item",
      item_count_other: "{count} items",
      title: "Products",
      add_label: "Add a product",
      search_placeholder: "Search name, brand, or barcode",
      clear_search: "Clear search",
      all: "All",
      result_count_one: "1 record",
      result_count_other: "{count} records",
      empty_title: "Add your first product",
      empty_description: "Scan a barcode or enter a product name to save it.",
      no_results_title: "No matches",
      no_results_description: "Try a different search or rating filter.",
    },
    scan: {
      permission_icon_label: "Camera",
      permission_title: "Scan a barcode with your camera",
      permission_description: "Allow camera access to find products quickly.",
      allow_camera: "Allow camera",
      open_settings: "Open settings",
      preparing_camera: "Preparing camera…",
      close: "Close scanner",
      title: "Scan a barcode",
      helper: "Align a JAN, EAN, or UPC barcode inside the frame",
      manual_title: "Enter the number",
      barcode_placeholder: "Barcode number",
      search: "Search barcode",
      finding: "Checking product information…",
    },
    form: {
      loading: "Loading product…",
      create_title: "Add product",
      edit_title: "Edit product",
      create_heading: "Leave a note for your future self.",
      edit_heading: "Keep the record current.",
      create_description:
        "You can change the rating later. Save how it feels today.",
      edit_description: "Update the rating or note to match how you feel now.",
      lookup_title: "Checking product information",
      lookup_description:
        "Found information will be added as a suggestion. Review it before saving.",
      lookup_not_found:
        "No product information was found. You can enter it manually.",
      lookup_failed:
        "Product information could not be retrieved. You can enter it manually.",
      auto_fill_title: "Product information added",
      auto_fill_description:
        "This information came from Open Food Facts. Review it before saving.",
      image_change: "Change photo",
      image_add: "Add product photo",
      image_remove: "Remove photo",
      product_name: "Product name",
      product_name_placeholder: "e.g. Unsweetened latte",
      barcode: "Barcode",
      barcode_placeholder: "Scan or enter",
      brand: "Brand",
      brand_placeholder: "e.g. Brand name",
      rating: "Rating",
      note: "Note",
      note_placeholder: "Taste, how it worked, where you bought it…",
      saving: "Saving…",
      register: "Add product",
      save_changes: "Save changes",
    },
    detail: {
      load_failed: "Could not load the product.",
      not_found: "Product not found",
      back_to_products: "Back to products",
      delete_title: "Delete this product?",
      delete_description: "This record cannot be restored.",
      delete_failed: "Could not delete the product.",
      title: "Product details",
      edit_label: "Edit product",
      next_buy: "Next time",
      avoid_next: "Skip next time",
      current_rating: "Current rating",
      note_label: "Note",
      no_note: "No note yet.",
      registered_at: "Added",
      updated_at: "Updated",
      edit_record: "Edit this record",
      delete_product: "Delete this product",
    },
    errors: {
      barcode_required: "Enter a barcode.",
      product_name_required: "Enter a product name.",
      product_name_too_long: "Product names must be 120 characters or fewer.",
      brand_too_long: "Brands must be 100 characters or fewer.",
      note_too_long: "Notes must be 2,000 characters or fewer.",
      barcode_digits_only: "Barcodes can contain digits only.",
      lookup_failed: "Could not search for the product. Try again.",
      product_not_found: "Product not found.",
      product_load_failed: "Could not load the product.",
      photo_select_failed: "Could not select a photo. Try again.",
      save_failed: "Could not save the product.",
      register_failed: "Could not add the product.",
      duplicate_barcode:
        "This barcode is already registered. Edit the existing record instead.",
    },
    database: {
      load_failed_title: "Could not load your records",
      load_failed_description:
        "If restarting the app does not help, check the available storage on your device.",
    },
    settings: {
      title: "Settings",
      language_title: "App language",
      language_description:
        "Choose the language used by the app. System uses your device language.",
      system: "System",
      system_description:
        "Japanese devices use 日本語. Other devices use English.",
      japanese: "日本語",
      japanese_description: "Display the app in Japanese.",
      english: "English",
      english_description: "Display the app in English.",
      current: "Current setting: {language}",
      product_language_note:
        "Barcode lookups also prioritize product names in this language.",
      language_save_failed: "The display language could not be saved.",
      data_title: "Data and privacy",
      data_description:
        "Product records and photos stay on this device. Uninstalling the app may remove them.",
      privacy_policy: "Privacy policy",
      privacy_description:
        "See what is stored and when an external service is contacted.",
      terms: "Terms of use",
      terms_description: "See the app terms and one-time unlock conditions.",
      accessibility: "Accessibility",
      accessibility_description:
        "See supported interactions, alternatives, and contact details.",
      attribution_title: "Product information source",
      attribution_description:
        "Open Food Facts provides product name, brand, and image suggestions.",
      attribution_link: "Open Open Food Facts",
    },
    purchase: {
      title: "One-time unlock",
      description:
        "The free version supports up to 20 products. A one-time purchase removes the registration limit.",
      price: "Price: {price}",
      price_unavailable: "The price is shown by the store",
      unlocked: "Unlocked",
      unlock: "Unlock with one-time purchase",
      restore: "Restore purchase",
      dev_build_required:
        "Purchases are available in a physical App Store or Google Play build.",
      limit_title: "Free registration limit reached",
      limit_description:
        "The free version supports up to {count} products. You can still view, edit, and delete existing records.",
      limit_blocked: "A one-time unlock is required to add another product.",
      purchase_failed: "The purchase could not be completed.",
      restore_failed: "The purchase could not be restored.",
      finish_failed: "The purchase could not be confirmed.",
      store_unavailable: "Could not connect to the purchase store.",
    },
    terms: {
      title: "Terms of use",
      intro:
        "buy-again is a personal memo app for recording impressions of products you bought.",
      use_title: "Service scope",
      use_body:
        "The app is not an inventory, ordering, accounting, or quality-control system. Do not use records as a basis for food safety, allergy, health, or medical decisions.",
      storage_title: "Data storage",
      storage_body:
        "Records and photos are stored on the device. Persistence, integrity, availability, and recovery are not guaranteed. Data may be lost through device failure, loss, OS processing, or app deletion. Do not use this app as your only storage.",
      external_title: "External services",
      external_body:
        "Open Food Facts is used for barcode lookup. The accuracy, completeness, and freshness of its information are not guaranteed. Network failures, outages, and changes may make it unavailable.",
      purchase_title: "One-time unlock",
      purchase_body:
        "The free version supports up to 20 new product registrations. The one-time unlock is not a subscription. Price, tax, refunds, purchase history, and restoration follow the store terms and applicable law.",
      disclaimer_title: "Disclaimers and liability",
      disclaimer_body:
        "To the extent permitted by law, the developer is not liable for damage arising from use of the app or external services. This excludes liability that cannot be limited by law, or liability for wilful misconduct or gross negligence.",
      changes_title: "Changes to these terms",
      changes_body:
        "These terms may be changed when necessary. Updated terms apply when announced in the app or on its distribution page.",
      law_title: "Governing law and jurisdiction",
      law_body:
        "These terms are governed by the laws of Japan. Disputes are handled by the court with jurisdiction under applicable law.",
      contact_title: "Contact",
      contact_body:
        "Developer: naoki-webdev\nContact: https://github.com/naoki-webdev/buy-again/issues",
    },
    accessibility: {
      title: "Accessibility",
      intro:
        "We continue improving screens for VoiceOver and TalkBack, larger text sizes, and layouts that remain understandable across screen sizes.",
      interaction_title: "Interaction and display",
      interaction_body:
        "Meaningful controls have spoken names, and ratings are identified by labels as well as color. We continue checking behavior with larger text and different screen sizes.",
      alternative_title: "Alternatives",
      alternative_body:
        "Barcodes can be entered manually without using the camera. You can use manual entry and save records without photos when camera or photo access is not granted.",
      standard_title: "Reference standard",
      standard_body:
        "WCAG 2.2 AA is used as a reference. This is not a claim that the app fully conforms to that standard.",
      contact_title: "Contact",
      contact_body:
        "Please send accessibility issues or suggestions to https://github.com/naoki-webdev/buy-again/issues.",
    },
    privacy: {
      title: "Privacy and data",
      intro:
        "buy-again is a personal app for keeping shopping memories on your device.",
      local_title: "Information stored on this device",
      local_body:
        "The app stores product names, brands, barcodes, ratings, notes, creation and update dates, and product photos on the device. Product records and product photos saved in the app, including photos selected by the user and images retrieved from Open Food Facts, are not sent to the developer's servers. Product records remain on the device until the user deletes them in the app or uninstalls the app. The app does not require an account and does not use advertising, analytics, or cloud synchronization to servers operated by the developer. Depending on your device's OS backup settings, Google or Apple backup services may include this data.",
      network_title: "Open Food Facts requests",
      network_body:
        "When checking an unregistered food barcode, the app sends the barcode number and display language to Open Food Facts. Product records and photos are not included in search requests. API requests also include a User-Agent containing the app name, version, and public repository URL. You can review and edit returned names, brands, and images before saving. Open Food Facts' Privacy Policy and Terms of Use apply to the retention and deletion of information on that service. The buy-again developer does not manage information stored by Open Food Facts.",
      permissions_title: "Device permissions",
      permissions_body:
        "The camera is used when scanning barcodes. Photo access is used when selecting a product photo. You can still enter barcodes manually and register products without photos if you do not grant these permissions. Camera and photo access permissions can be changed or revoked at any time in the device settings.",
      security_title: "Secure handling",
      security_body:
        "Product records and photos are stored in the app-specific storage area on the device. The app uses HTTPS for communication with Open Food Facts.",
      deletion_title: "Deletion",
      deletion_body:
        "You can delete a product record from the product detail screen. Deleting a product record also deletes the product photo saved on the device by buy-again. For deletion requests concerning a barcode sent to Open Food Facts or questions about its data processing, use the contact methods described in the Open Food Facts Privacy Policy.",
      third_party_title: "Third-party service and licenses",
      third_party_body:
        "Product information is provided using data from Open Food Facts. The database is provided under the Open Database License (ODbL), individual database contents under the Database Contents License, and product images under the Creative Commons Attribution-ShareAlike (CC BY-SA) terms. See the Open Food Facts official site for license details and reuse conditions.",
      purchase_title: "App Store and Google Play purchases",
      purchase_body:
        "If you use the one-time unlock, Apple or Google processes the payment information. The buy-again developer does not receive card details. The app uses purchase information provided by the stores to check the unlock state. The stores' privacy policies and terms apply to purchases, refunds, and billing history.",
      contact_title: "Developer information and contact",
      contact_body:
        "Developer: naoki-webdev\nPrivacy inquiries: https://github.com/naoki-webdev/buy-again/issues",
      off_link: "Open the Open Food Facts site",
    },
    messages: {
      product_created: "Product added",
      product_updated: "Changes saved",
      product_deleted: "Product deleted",
    },
  },
} as const;
