import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import YAML from "yaml";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.dirname(scriptDirectory);
const localesDirectory = path.join(projectDirectory, "src", "locales");
const localeNames = ["ja", "en"];
const localeData = {};

for (const localeName of localeNames) {
  const source = fs.readFileSync(
    path.join(localesDirectory, `${localeName}.yml`),
    "utf8",
  );
  const parsed = YAML.parse(source, { maxAliasCount: 0 });
  if (!isRecord(parsed)) {
    throw new Error(`${localeName}.yml must contain a mapping at the root.`);
  }
  localeData[localeName] = parsed;
}

const localeKeys = localeNames.map((localeName) => ({
  localeName,
  keys: getLeafKeys(localeData[localeName]),
}));
const referenceKeys = localeKeys[0].keys;
const referenceKeySet = new Set(referenceKeys);
const mismatches = localeKeys.flatMap(({ localeName, keys }) => {
  const keySet = new Set(keys);
  const missing = referenceKeys
    .filter((key) => !keySet.has(key))
    .map((key) => `${localeName}.yml is missing ${key}`);
  const extra = keys
    .filter((key) => !referenceKeySet.has(key))
    .map((key) => `${localeName}.yml has unexpected ${key}`);
  return [...missing, ...extra];
});

if (mismatches.length > 0) {
  throw new Error(`Locale key mismatch:\n${mismatches.join("\n")}`);
}

const output = `// This file is generated by scripts/generate-locales.mjs.\nexport const translations = ${JSON.stringify(localeData, null, 2)} as const;\n`;
const formattedOutput = await prettier.format(output, { parser: "typescript" });
fs.writeFileSync(path.join(localesDirectory, "generated.ts"), formattedOutput);

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function getLeafKeys(value, prefix = "") {
  if (!isRecord(value)) {
    return prefix.length > 0 ? [prefix] : [];
  }

  return Object.entries(value).flatMap(([key, child]) => {
    const childPrefix = prefix.length > 0 ? `${prefix}.${key}` : key;
    return getLeafKeys(child, childPrefix);
  });
}
