import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import YAML from "yaml";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.dirname(scriptDirectory);
const localesDirectory = path.join(projectDirectory, "src", "locales");
const localeNames = ["ja", "en"];
const localeData = {};

for (const localeName of localeNames) {
  const source = fs.readFileSync(
    path.join(localesDirectory, `${localeName}.yml`),
    "utf8",
  );
  const parsed = YAML.parse(source, { maxAliasCount: 0 });
  if (!isRecord(parsed)) {
    throw new Error(`${localeName}.yml must contain a mapping at the root.`);
  }
  localeData[localeName] = parsed;
}

const output = `// This file is generated by scripts/generate-locales.mjs.\nexport const translations = ${JSON.stringify(localeData, null, 2)} as const;\n`;
const formattedOutput = await prettier.format(output, { parser: "typescript" });
fs.writeFileSync(path.join(localesDirectory, "generated.ts"), formattedOutput);

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
